name: echidna
channels:
  - defaults
dependencies:
  - blas=1.0=openblas
  - bzip2=1.0.8=h620ffc9_4
  - ca-certificates=2023.12.12=hca03da5_0
  - click=8.1.7=py312hca03da5_0
  - expat=2.5.0=h313beb8_0
  - flask=2.2.5=py312hca03da5_0
  - freetype=2.12.1=h1192e45_0
  - imageio=2.33.1=py312hca03da5_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jinja2=3.1.3=py312hca03da5_0
  - jpeg=9e=h80987f9_1
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libtiff=4.5.1=h313beb8_0
  - libwebp-base=1.3.2=h80987f9_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_0
  - markupsafe=2.1.3=py312h80987f9_0
  - ncurses=6.4=h313beb8_0
  - numpy=1.26.4=py312h7f4fdc5_0
  - numpy-base=1.26.4=py312he047099_0
  - openjpeg=2.3.0=h7a6adac_2
  - openssl=3.0.13=h1a28f6b_0
  - pillow=10.2.0=py312h80987f9_0
  - pip=23.3.1=py312hca03da5_0
  - python=3.12.1=h99e199e_0
  - readline=8.2=h1a28f6b_0
  - setuptools=68.2.2=py312hca03da5_0
  - sqlite=3.41.2=h80987f9_0
  - tk=8.6.12=hb8d0fd4_0
  - tzdata=2024a=h04d1e81_0
  - werkzeug=2.3.8=py312hca03da5_0
  - wheel=0.41.2=py312hca03da5_0
  - xz=5.4.5=h80987f9_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.5=hd90d995_0
  - pip:
      - mahotas==1.4.13
      - peewee==3.17.1
